# Backend Dockerfile for NemoClaw-agritwin-dairy-agentic-ai-platform-backend
# Generated by AgriTwin Agent Factory

FROM node:20-alpine

WORKDIR /app

COPY package.json .
RUN npm install --production

COPY . .

EXPOSE 3000

CMD ["node", "src/index.mjs"]
