// runtime-server.mjs — generated by AgriTwin Agent Factory
// Long-running HTTP wrapper that keeps the container alive.

import http from 'node:http';
import { createServer } from 'node:http';

let app = null;
let loaded = false;
let loadError = null;

try {
  const mod = await import('./src/index.mjs');
  app = mod.default || mod.app || mod;
  loaded = true;
} catch (err) {
  loadError = err.message;
  console.error('[runtime-server] Failed to load app module:', err.message);
}

const server = createServer((req, res) => {
  const url = req.url.split('?')[0];
  const method = req.method;

  if (url === '/health' || url === '/ready') {
    const status = loaded ? 200 : 503;
    res.writeHead(status, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      status: loaded ? 'healthy' : 'unhealthy',
      loaded,
      error: loadError || null,
      service: 'NemoClaw-agritwin-dairy-agentic-ai-platform-backend',
      type: 'backend',
    }));
    return;
  }

  
  if (url === '/api/farm/status') {
    if (method !== 'GET') {
      res.writeHead(405, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: 'Method not allowed' }));
      return;
    }
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      route: '/api/farm/status',
      service: 'NemoClaw-agritwin-dairy-agentic-ai-platform-backend',
      type: 'backend',
      timestamp: new Date().toISOString(),
      status: 'success'
    }));
    return;
  }
  if (url === '/api/farm/kpis') {
    if (method !== 'GET') {
      res.writeHead(405, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: 'Method not allowed' }));
      return;
    }
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      route: '/api/farm/kpis',
      service: 'NemoClaw-agritwin-dairy-agentic-ai-platform-backend',
      type: 'backend',
      timestamp: new Date().toISOString(),
      status: 'success'
    }));
    return;
  }
  if (url === '/api/farm/zones') {
    if (method !== 'GET') {
      res.writeHead(405, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: 'Method not allowed' }));
      return;
    }
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      route: '/api/farm/zones',
      service: 'NemoClaw-agritwin-dairy-agentic-ai-platform-backend',
      type: 'backend',
      timestamp: new Date().toISOString(),
      status: 'success'
    }));
    return;
  }
  if (url === '/api/agents/activity') {
    if (method !== 'GET') {
      res.writeHead(405, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: 'Method not allowed' }));
      return;
    }
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      route: '/api/agents/activity',
      service: 'NemoClaw-agritwin-dairy-agentic-ai-platform-backend',
      type: 'backend',
      timestamp: new Date().toISOString(),
      status: 'success'
    }));
    return;
  }
  if (url === '/api/alerts') {
    if (method !== 'GET') {
      res.writeHead(405, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: 'Method not allowed' }));
      return;
    }
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      route: '/api/alerts',
      service: 'NemoClaw-agritwin-dairy-agentic-ai-platform-backend',
      type: 'backend',
      timestamp: new Date().toISOString(),
      status: 'success'
    }));
    return;
  }
  if (url === '/api/config') {
    if (method !== 'GET') {
      res.writeHead(405, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: 'Method not allowed' }));
      return;
    }
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      route: '/api/config',
      service: 'NemoClaw-agritwin-dairy-agentic-ai-platform-backend',
      type: 'backend',
      timestamp: new Date().toISOString(),
      status: 'success'
    }));
    return;
  }

  if (url === '/' || url === '/index.html') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      service: 'NemoClaw-agritwin-dairy-agentic-ai-platform-backend',
      type: 'backend',
      loaded,
      app: app || null,
      available_routes: ['/api/farm/status', '/api/farm/kpis', '/api/farm/zones', '/api/agents/activity', '/api/alerts', '/api/config'],
    }));
    return;
  }

  res.writeHead(404, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({ error: 'Not found' }));
});

server.listen(3000, '0.0.0.0', () => {
  console.log('[runtime-server] NemoClaw-agritwin-dairy-agentic-ai-platform-backend listening on 0.0.0.0:3000');
  console.log('[runtime-server] App loaded:', loaded);
  if (loadError) console.log('[runtime-server] Load error:', loadError);
});

// Keep the process alive even if the app module does not start a server.
setInterval(() => {}, 60 * 60 * 1000);
