// animals route
// Generated by AgriTwin Agent Factory

import { Cow, Herd } from '@robo-jedi-pl/agritwin-shared/entities/index.mjs';

export function getAnimals(req, res) {
  return { entities: [Cow.name, Herd.name] };
}

export default { getAnimals };
