// health route
// Generated by AgriTwin Agent Factory

import { HealthAlert } from '@robo-jedi-pl/agritwin-shared/entities/index.mjs';

export function getHealthAlerts(req, res) {
  return { entity: HealthAlert.name };
}

export default { getHealthAlerts };
