// milk-yield route
// Generated by AgriTwin Agent Factory

import { MilkYield } from '@robo-jedi-pl/agritwin-shared/entities/index.mjs';

export function getMilkYields(req, res) {
  return { entity: MilkYield.name };
}

export default { getMilkYields };
