// recommendations route
// Generated by AgriTwin Agent Factory

import { AgentRecommendation } from '@robo-jedi-pl/agritwin-shared/entities/index.mjs';

export function getRecommendations(req, res) {
  return { entity: AgentRecommendation.name };
}

export default { getRecommendations };
