// dairy-agent orchestrator
// Generated by AgriTwin Agent Factory

import { Cow, HealthAlert, AgentRecommendation } from '@robo-jedi-pl/agritwin-shared/entities/index.mjs';

export class DairyAgent {
  async analyse(cowId) {
    return {
      cowId,
      recommendation: AgentRecommendation.name,
      alert: HealthAlert.name,
    };
  }
}

export default DairyAgent;
