// NemoClaw-agritwin-dairy-agentic-ai-platform-backend — Backend entry point
// Generated by AgriTwin Agent Factory

import { entities } from '@robo-jedi-pl/agritwin-shared/entities/index.mjs';

export const app = {
  name: 'NemoClaw-agritwin-dairy-agentic-ai-platform-backend',
  type: 'backend',
  modules: ["api-gateway","ml-inference","agent-orchestrator"],
  entityCount: entities.length,
};

export default app;
